[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.2", "setuptools_scm[toml]>=8.0"]

[project]
name = "thermoextrap"
description = "Thermodynamic extrapolation"
keywords = ["thermoextrap"]
license = { text = "NIST-PD" }
authors = [
    { name = "Jacob Monroe", email = "jacob.monroe@nist.gov" },
    { name = "William Krekelberg", email = "wpk@nist.gov" }
]
requires-python = ">=3.8,<3.12"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "License :: Public Domain",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering",
]
dynamic = ["readme", "version"]
dependencies = [
    "attrs",
    "cmomy >= 0.5",
    "custom-inherit",
    "lazy_loader",
    "module-utilities >= 0.2",
    "numpy >= 1.20",
    "scipy",
    "sympy",
    "xarray >= 0.16",
]

[project.optional-dependencies]
accel = ["bottleneck"]
all = [
    "thermoextrap[mbar]",
    "thermoextrap[gpr]",
    "thermoextrap[accel]",
    "thermoextrap[parallel]",
    "thermoextrap[viz]",
]
dev = [
    "thermoextrap[test]", #
    "thermoextrap[typing-extras]",
    "thermoextrap[dev-extras]",
    "thermoextrap[accel]",
    "thermoextrap[viz]",
]
dev-complete = [
    "thermoextrap[dev]", #
    "thermoextrap[tools]",
    "thermoextrap[nox]",
]
dev-extras = [
    "ipykernel", # "nbval",
    "ipython",
    "pytest-accept", #
    "setuptools-scm>=8.0", #

]
dist-conda = [
    "anaconda-client", #
    "boa",
    "conda-build",
    "conda-verify",
    "grayskull",
]
dist-pypi = ["build", "twine"]
docs = [
    "autodocsumm",
    "ghp-import",
    "ipython", #
    "myst-nb",
    "pyenchant",
    "sphinx >= 5.3.0",
    "sphinx-autobuild",
    "sphinx-book-theme",
    "sphinx-copybutton",
    "sphinxcontrib-spelling",
    "thermoextrap[viz]",
    "thermoextrap[mbar]",
    "thermoextrap[gpr]",
]
gpr = [
    "gpflow >= 2.6.0", #
    "tensorflow", #
    "tensorflow-probability", #

]
mbar = ["pymbar>=4.0"]
nox = [
    "nox",
    "noxopt", #
    "ruamel.yaml",
]
openmm = ["openmm"]
parallel = [
    "dask[complete]", # p2c: -s dask

]
test = [
    "pandas",
    "pytest", #
    "pytest-cov",
    "pytest-sugar",
    "pytest-xdist",
    "thermoextrap[mbar]",
    "thermoextrap[gpr]",
]
tools = [
    "nbqa",
    "pre-commit", #  "cruft",
    "pyright",
    "scriv", # p2c: -p

]
typing = [
    "thermoextrap[typing-extras]", #
    "thermoextrap[test]",
]
typing-extras = [
    "mypy >= 1.4.1",
    "pytype; python_version < '3.11'", #

]
viz = ["matplotlib"]

[project.urls]
documentation = "https://pages.nist.gov/thermoextrap/"
homepage = "https://github.com/usnistgov/thermoextrap"

[tool.setuptools]
zip-safe = true # if using mypy, must be False
include-package-data = true
license-files = ["LICENSE"]

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

## include = []
## exclude = []
[tool.setuptools.dynamic]
readme = { file = [
    "README.md",
    "CHANGELOG.md",
    "LICENSE"
], content-type = "text/markdown" }

[tool.setuptools_scm]
fallback_version = "999"

[tool.ruff]
fix = true
line-length = 88
target-version = "py38"
select = [
    # pyflakes
    "F",
    # pycodestyle
    "E",
    "W",
    # isort
    "I",
    # pyupgrade
    "UP",
    # pydocstyle
    "D",
    # # flake8-2020
    "YTT",
    # # flake8-bugbear
    # "B",
    # flake8-quotes
    "Q",
    # # pylint
    # "PLE", "PLR", "PLW",
    # # misc lints
    "PIE",
    # # tidy imports
    "TID",
    # # implicit string concatenation
    # "ISC",
    # # type-checking imports
    "TCH",
]
# Allow autofix for all enabled rules (when `--fix`) is provided.
# fixable = ["A", "B", "C", "D", "E", "F", "..."]
unfixable = []
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "docs/conf.py",
    "src/thermoextrap/tests",
    "tests/",
    "src/thermoextrap/legacy/",
    "examples/gpr_active_learning/",
]
ignore = [
    # # whitespace before ':' - doesn't work well with black
    # "E203",
    # module level import not at top of file
    "E402",
    # line too long - let black worry about that
    "E501",
    # do not assign a lambda expression, use a def
    "E731",
    # # line break before binary operator
    # "W503",
    # allow black line after docstring
    "D202",
    "D105",
    "D205",
    # this leads to errors with placing titles in module
    # docstrings
    "D400",
    "D401",
    "D415",
    "D102",
    "D103",
    # these are useful, but too many errors
    # due to use of docfiller
    "D417",
    "D107",
    "D203",
    "D212",
    # Allow relative imports
    "TID252",
]
per-file-ignores = {  }
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.isort]
known-first-party = ["thermoextrap"]

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

# TODO : Fix examples/gpr_active_learning/analysis_polymer.ipynb F821
# beta_list data_list
[tool.isort]
profile = "black"
skip_gitignore = true
known_first_party = ["thermoextrap"]

[tool.flake8]
docstring-convention = "numpy"
ignore = [
    # # whitespace before ':' - doesn't work well with black
    "E203",
    # module level import not at top of file
    "E402",
    # line too long - let black worry about that
    "E501",
    # do not assign a lambda expression, use a def
    "E731",
    # # line break before binary operator
    "W503",
    # allow black line after docstring
    "D202",
    "D105",
    "D205",
    # this leads to errors with placing titles in module
    # docstrings
    "D400",
    "D401",
    "D415",
    "D102",
    "D103",
    # these are useful, but too many errors
    # due to use of docfiller
    "D417",
    "D107",
    "D203",
    "D212",
]

[tool.nbqa.addopts]
ruff = ["--fix", "--extend-ignore=D100,B018,F821"]

[tool.pytest.ini_options]
addopts = "--doctest-modules --doctest-glob='*.md'"
testpaths = ["tests", "README.md"]

[tool.coverage.report]
exclude_also = ["if TYPE_CHECKING:", "@overload"]
omit = ["*/vendored/*"]
include = ["src/*"]

[tool.mypy]
files = ["src", "tests", "noxfile.py", "tools"]
show_error_codes = true
warn_unused_ignores = true
warn_return_any = true
warn_unused_configs = true
exclude = [".eggs", ".tox", "doc", "docs", ".nox"]
check_untyped_defs = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = []

[[tool.mypy.overrides]]
ignore_errors = true
module = []

[tool.pyright]
include = ["src", "tests"]
exclude = [
    "**/__pycache__",
    ".tox/**",
    ".nox/**",
    "**/.mypy_cache",
    "dist-conda",
    "examples"
]
pythonVersion = "3.10"
typeCheckingMode = "basic"
useLibraryCodeForTypes = false
# enable subset of "strict"
reportDuplicateImport = true
reportInvalidStubStatement = true
reportOverlappingOverload = true
reportPropertyTypeMismatch = true
reportUntypedClassDecorator = true
reportUntypedFunctionDecorator = true
reportUntypedNamedTuple = true
reportUnusedImport = true
# disable subset of "basic"
reportGeneralTypeIssues = false
reportMissingModuleSource = false
reportOptionalCall = false
reportOptionalIterable = false
reportOptionalMemberAccess = false
reportOptionalOperand = false
reportOptionalSubscript = false
reportPrivateImportUsage = false
reportUnboundVariable = false

[tool.pyproject2conda]
user_config = "config/userconfig.toml"
template_python = "requirements/py{py}-{env}"
template = "requirements/{env}"
# defaults
python = ["3.10"]
channels = ["conda-forge"]
style = ["yaml", "requirements"]
default_envs = [
    "test",
    "typing",
    "docs",
    "dev",
    "dev-complete",
    "dist-conda",
    "dist-pypi"
]

[tool.pyproject2conda.dependencies]
pytest-accept = { pip = true }
scriv = { pip = true }
gpflow = { pip = true }
tensorflow = { pip = true }
tensorflow-probability = { pip = true }

[tool.pyproject2conda.envs.test-extras]
extras = ["test"]

[tool.pyproject2conda.envs.dev-base]
extras = ["dev"]

[[tool.pyproject2conda.overrides]]
envs = ["test-extras", "dist-conda", "dist-pypi"]
base = false

[[tool.pyproject2conda.overrides]]
envs = ["test", "typing", "test-extras"]
python = ["3.8", "3.9", "3.10", "3.11"]

[[tool.pyproject2conda.overrides]]
envs = ["dist-conda"]
style = ["yaml"]

## grayskull still messes some things up, but use scripts/recipe-append.sh for this
[tool.aliases]
test = "pytest"

[tool.scriv]
format = "md"
md_header_level = "2"
new_fragment_template = "file: changelog.d/templates/new_fragment.md.j2"

[tool.commitizen]
use_shortcuts = true

[tool.cruft]

[tool.pytype]
inputs = ["src", "tests"]
