[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=61.2",
    "setuptools_scm[toml]>=8.0",
]

[project]
name = "thermoextrap"
description = "Thermodynamic extrapolation"
keywords = [
    "thermoextrap",
]
license = { text = "NIST-PD" }
authors = [
    { name = "Jacob Monroe", email = "jacob.monroe@nist.gov" },
    { name = "William Krekelberg", email = "wpk@nist.gov" }
]
requires-python = ">=3.8,<3.12"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "License :: Public Domain",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering",
]
dynamic = [
    "readme",
    "version",
]
dependencies = [
    "attrs",
    "cmomy >= 0.5",
    "custom-inherit",
    "lazy_loader",
    "module-utilities >= 0.2",
    "numpy >= 1.20",
    "scipy",
    "sympy",
    "xarray >= 0.16",
]
[project.optional-dependencies]
accel = [
    "bottleneck",
]
all = [
    "thermoextrap[mbar]",
    "thermoextrap[gpr]",
    "thermoextrap[accel]",
    "thermoextrap[parallel]",
    "thermoextrap[viz]",
]
dev = [
    "thermoextrap[nbval]",
    "thermoextrap[test]",
    "thermoextrap[typing-extras]",
    "thermoextrap[dev-extras]",
    "thermoextrap[accel,viz]",
]
dev-complete = [
    "thermoextrap[dev]",
    "thermoextrap[tools]",
]
dev-extras = [
    "ipykernel",
    "ipython",
    "nox",
    "pytest-accept",
]
docs = [
    "autodocsumm",
    "ghp-import",
    "ipython",
    "myst-nb",
    "pyenchant",
    "sphinx >= 5.3.0",
    "sphinx-autobuild",
    "sphinx-book-theme",
    "sphinx-copybutton",
    "sphinxcontrib-spelling",
    "thermoextrap[gpr,mbar,viz]",
]
gpr = [
    "gpflow >= 2.6.0",
    "tensorflow",
    "tensorflow-probability",
]
mbar = [
    "pymbar>=4.0",
]
nbval = [
    "nbval",
]
openmm = [
    "openmm",
]
parallel = [
    "dask[complete]",
]
test = [
    "pandas",
    "pytest",
    "pytest-cov",
    "pytest-sugar",
    "pytest-xdist",
    "thermoextrap[mbar,gpr]",
]
tools = [
    "nbqa",
    "pip-tools",
    "pre-commit",
    "pyright",
    "scriv",
]
typing = [
    "pandas",
    "pytest",
    "thermoextrap[typing-extras]",
    "thermoextrap[mbar,gpr]",
]
typing-extras = [
    "mypy >= 1.4.1",
    "pytype; python_version < '3.11'",
]
viz = [
    "matplotlib",
]
[project.urls]
Documentation = "https://pages.nist.gov/thermoextrap/"
Homepage = "https://github.com/usnistgov/thermoextrap"

[tool.setuptools]
zip-safe = true # if using mypy, must be False
include-package-data = true
license-files = ["LICENSE"]

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.setuptools.dynamic]
readme = { file = [
    "README.md",
    "CHANGELOG.md",
    "LICENSE"
], content-type = "text/markdown" }

[tool.setuptools_scm]
fallback_version = "999"

# * Linting --------------------------------------------------------------------

[tool.ruff]
fix = true
line-length = 88
target-version = "py38"
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "tests/",
    "src/thermoextrap/tests",
    "src/thermoextrap/legacy/",
    "examples/gpr_active_learning/",
]

[tool.ruff.lint]
select = [
    "F",      ## pyflakes
    "E", "W", ## pycodestyle
    "I",      ## isort
    "UP",     ## pyupgrade
    "D",      ## pydocstyle
    "YTT",    ## flake8-2020
    # "B",    ## flake8-bugbear
    "Q",      ## flake8-quotes
    # "PLE",  ## pylint
    # "PLR"   ## pylint
    # "PLW",  ## pylint
    "PIE",    ## misc lints
    "TID",    ## tidy imports
    # "ISC",  ## implicit string concatenation
    "TCH",    ## type-checking imports
]
# Allow autofix for all enabled rules (when `--fix`) is provided.
# fixable = ["A", "B", "C", "D", "E", "F", "..."]
unfixable = []
# Exclude a variety of commonly ignored directories.
ignore = [
    # "E203", ## whitespace before ':' - doesn't work well with black
    "E402",   ## module level import not at top of file
    "E501",   ## line too long - let black worry about that
    "E731",   ## do not assign a lambda expression, use a def
    # "W503", ## line break before binary operator
    "D202",   ## blank line after docstring
    "D105",   ## Missing magic method docstring
    "D205",   ## blank line after summary
    # this leads to errors with placing titles in module
    "D400",   ## First line should end with a period
    "D401",   ## First line of docstring should be in imperative mood: "{first_line}"
    "D415",   ## First line should end with a period, question mark, or exclamation point
    "D102",   ## Missing docstring in public method
    "D103",   ## Missing docstring in public function
    # these are useful, but too many errors with docfiller
    "D417",   ## Missing argument description in the docstring for {definition}: {name}
    "D107",   ## Missing docstring in __init__
    "D203",   ## 1 blank line required before class docstring
    "D212",   ## Multi-line docstring summary should start at the first line
    "TID252", ## Allow relative imports
]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
# per-file-ignores = {  }

[tool.ruff.lint.isort]
known-first-party = ["thermoextrap"]

[tool.ruff.format]
docstring-code-format = true

[tool.nbqa.addopts]
ruff = ["--fix", "--extend-ignore=D100,B018,F821"]

# * Testing --------------------------------------------------------------------

[tool.pytest.ini_options]
addopts = "--doctest-modules --doctest-glob='*.md' --ignore-glob='**/legacy/**' --pyargs"
testpaths = ["thermoextrap", "tests", "README.md"]

[tool.coverage.report]
exclude_also = ["if TYPE_CHECKING:", "@overload"]
omit = ["*/vendored/*", "*/_typing.py"]
include = ["src/*"]

[tool.coverage.paths]
source = ["src/", ".nox/**/site-packages/"]

# * Typing

[tool.mypy]
files = ["src", "tests"]
show_error_codes = true
warn_unused_ignores = true
warn_return_any = true
warn_unused_configs = true
exclude = [".eggs", ".tox", "doc", "docs", ".nox"]
check_untyped_defs = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = []

[[tool.mypy.overrides]]
ignore_errors = true
module = []

[tool.pyright]
include = ["src", "tests"]
exclude = ["**/__pycache__", ".tox/**", ".nox/**", "**/.mypy_cache", "dist-conda", "examples"]
pythonVersion = "3.11"
typeCheckingMode = "basic"
# enable subset of "strict"
reportDuplicateImport = true
reportInvalidStubStatement = true
reportOverlappingOverload = true
reportPropertyTypeMismatch = true
reportUntypedClassDecorator = true
reportUntypedFunctionDecorator = true
reportUntypedNamedTuple = true
reportUnusedImport = true
# disable subset of "basic"
reportGeneralTypeIssues = false
reportMissingModuleSource = false
reportOptionalCall = false
reportOptionalIterable = false
reportOptionalMemberAccess = false
reportOptionalOperand = false
reportOptionalSubscript = false
reportPrivateImportUsage = false
reportUnboundVariable = false

[tool.pytype]
inputs = ["src", "tests"]

# * Dependency creation --------------------------------------------------------

[tool.pyproject2conda]
user_config = "config/userconfig.toml"
template_python = "requirements/py{py}-{env}"
template = "requirements/{env}"
python = ["3.11"]
channels = ["conda-forge"]
style = ["yaml", "requirements"]
default_envs = ["test", "typing", "docs", "dev", "dev-complete"]

[tool.pyproject2conda.dependencies]
pytest-accept = { pip = true }
scriv = { pip = true }
dask = { skip = true, packages = "dask" }
matplotlib = { skip = true, packages = "matplotlib-base" }
gpflow = { pip = true }
tensorflow = { pip = true }
tensorflow-probability = { pip = true }

[tool.pyproject2conda.envs.build]
extras = "build-system.requires"
reqs = ["build"]
base = false
style = "requirements"

[tool.pyproject2conda.envs.test-extras]
extras = ["test"]
base = false

[tool.pyproject2conda.envs.test-notebook]
extras = ["test", "nbval"]

[[tool.pyproject2conda.overrides]]
# Ensure these have pip in yaml file
envs = ["test", "docs", "dev", "dev-complete"]
deps = ["pip"]

[[tool.pyproject2conda.overrides]]
envs = ["test", "typing", "test-extras"]
python = ["3.8", "3.9", "3.10", "3.11"]

[tool.pip-tools]
allow-unsafe = true
strip-extras = true

# * Other tools ----------------------------------------------------------------

[tool.scriv]
format = "md"
md_header_level = "2"
new_fragment_template = "file: changelog.d/templates/new_fragment.md.j2"

[tool.commitizen]
use_shortcuts = true

[tool.cruft]
